//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Script/AbilityContainer/AbilityPopup/PopupScripts/PopupInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PopupInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PopupInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PopupInput"",
    ""maps"": [
        {
            ""name"": ""ActivatePopup"",
            ""id"": ""124930c8-efe9-4420-9d90-9780805c778d"",
            ""actions"": [
                {
                    ""name"": ""Popup"",
                    ""type"": ""Button"",
                    ""id"": ""7fff5eeb-eab6-408c-b8fa-b7453bc2b6ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""52ca6a83-bd64-4e99-92e9-46560498b3ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""29eef2c6-c834-4761-9504-209a05951c9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""212910cd-3b49-4b96-9bd6-76d77a72d4ce"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Popup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08ff3d0c-89f8-48b2-acf4-847491f778f4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4efd48d-72c5-4d7f-b732-eb0b2a3255d4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ActivatePopup
        m_ActivatePopup = asset.FindActionMap("ActivatePopup", throwIfNotFound: true);
        m_ActivatePopup_Popup = m_ActivatePopup.FindAction("Popup", throwIfNotFound: true);
        m_ActivatePopup_LeftClick = m_ActivatePopup.FindAction("LeftClick", throwIfNotFound: true);
        m_ActivatePopup_RightClick = m_ActivatePopup.FindAction("RightClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ActivatePopup
    private readonly InputActionMap m_ActivatePopup;
    private List<IActivatePopupActions> m_ActivatePopupActionsCallbackInterfaces = new List<IActivatePopupActions>();
    private readonly InputAction m_ActivatePopup_Popup;
    private readonly InputAction m_ActivatePopup_LeftClick;
    private readonly InputAction m_ActivatePopup_RightClick;
    public struct ActivatePopupActions
    {
        private @PopupInput m_Wrapper;
        public ActivatePopupActions(@PopupInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Popup => m_Wrapper.m_ActivatePopup_Popup;
        public InputAction @LeftClick => m_Wrapper.m_ActivatePopup_LeftClick;
        public InputAction @RightClick => m_Wrapper.m_ActivatePopup_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_ActivatePopup; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActivatePopupActions set) { return set.Get(); }
        public void AddCallbacks(IActivatePopupActions instance)
        {
            if (instance == null || m_Wrapper.m_ActivatePopupActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ActivatePopupActionsCallbackInterfaces.Add(instance);
            @Popup.started += instance.OnPopup;
            @Popup.performed += instance.OnPopup;
            @Popup.canceled += instance.OnPopup;
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
        }

        private void UnregisterCallbacks(IActivatePopupActions instance)
        {
            @Popup.started -= instance.OnPopup;
            @Popup.performed -= instance.OnPopup;
            @Popup.canceled -= instance.OnPopup;
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
        }

        public void RemoveCallbacks(IActivatePopupActions instance)
        {
            if (m_Wrapper.m_ActivatePopupActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IActivatePopupActions instance)
        {
            foreach (var item in m_Wrapper.m_ActivatePopupActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ActivatePopupActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ActivatePopupActions @ActivatePopup => new ActivatePopupActions(this);
    public interface IActivatePopupActions
    {
        void OnPopup(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
    }
}
